Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data_root = root + 'data/pool_fire/1mw_sealed'
sim = fdsreader.Simulation(data_root)
slice_temp = sim.slices[0]
time = 20
time_index = slice_temp.get_nearest_timestep(time)

plt.figure(figsize=(4,6))
plt.imshow(slice_temp[0].data[time_index].T, origin='lower', 
           extent=slice_temp[0].extent.as_list(), cmap='jet',
           vmin=20, vmax=1200)
plt.xlabel("X / m")
plt.ylabel("Z / m")
plt.colorbar(label="Temperature / $\sf ^\circ C$")
plt.savefig('figs/pool_fire_1mw_temperatures_slice.svg', bbox_inches='tight')
plt.close()


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m/tmp/ipykernel_1849/438644550.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mdata_root[0m [0;34m=[0m [0mroot[0m [0;34m+[0m [0;34m'data/pool_fire/1mw_sealed'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0msim[0m [0;34m=[0m [0mfdsreader[0m[0;34m.[0m[0mSimulation[0m[0;34m([0m[0mdata_root[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mslice_temp[0m [0;34m=[0m [0msim[0m[0;34m.[0m[0mslices[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mtime[0m [0;34m=[0m [0;36m20[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mtime_index[0m [0;34m=[0m [0mslice_temp[0m[0;34m.[0m[0mget_nearest_timestep[0m[0;34m([0m[0mtime[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/fdsreader/simulation.py[0m in [0;36m__new__[0;34m(cls, path)[0m
[1;32m     58[0m [0;34m[0m[0m
[1;32m     59[0m     [0;32mdef[0m [0m__new__[0m[0;34m([0m[0mcls[0m[0;34m,[0m [0mpath[0m[0;34m:[0m [0mstr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 60[0;31m         [0msmv_file_path[0m [0;34m=[0m [0mget_smv_file[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     61[0m         [0mroot_path[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mdirname[0m[0;34m([0m[0msmv_file_path[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     62[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/fdsreader/utils/data.py[0m in [0;36mget_smv_file[0;34m(path)[0m
[1;32m     90[0m             [0;32mraise[0m [0mIOError[0m[0;34m([0m[0;34m"There are multiple simulations in the directory: "[0m [0;34m+[0m [0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     91[0m         [0;32melif[0m [0mlen[0m[0;34m([0m[0mfiles[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 92[0;31m             [0;32mraise[0m [0mIOError[0m[0;34m([0m[0;34m"No simulations were found in the directory: "[0m [0;34m+[0m [0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     93[0m         [0;32mreturn[0m [0mfiles[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     94[0m     [0;32melif[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0misfile[0m[0;34m([0m[0mpath[0m [0;34m+[0m [0;34m".smv"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mOSError[0m: No simulations were found in the directory: ../../../../data/pool_fire/1mw_sealed
OSError: No simulations were found in the directory: ../../../../data/pool_fire/1mw_sealed

